# Generated by Django 3.1.3 on 2020-12-14 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=10, verbose_name='mes')),
                ('year', models.IntegerField(verbose_name='año')),
                ('model', models.CharField(max_length=100, verbose_name='modelo')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=250, verbose_name='text')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.date')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one_response', models.JSONField()),
                ('two_response', models.JSONField()),
                ('three_response', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('questions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question')),
            ],
            options={
                'verbose_name': 'Questionarie',
                'verbose_name_plural': 'Questionaries',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='responses',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.response'),
        ),
    ]
