# Generated by Django 3.1.3 on 2020-12-14 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='one_response',
            new_name='response',
        ),
        migrations.RemoveField(
            model_name='response',
            name='three_response',
        ),
        migrations.RemoveField(
            model_name='response',
            name='two_response',
        ),
    ]
