# Generated by Django 3.1.3 on 2020-12-14 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20201214_1529'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='response',
            new_name='responses',
        ),
    ]
