# Generated by Django 3.1.3 on 2020-12-14 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20201214_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='responses',
            field=models.JSONField(),
        ),
        migrations.DeleteModel(
            name='Response',
        ),
    ]
